package group_12;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import static group_12.DormitoryRentingSystem.my;
import javax.swing.JOptionPane;
public class Accounting extends javax.swing.JFrame {

    public Accounting() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Accounting_id_TextField = new javax.swing.JTextField();
        income_TextField = new javax.swing.JTextField();
        electronic_bill_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menu_Button = new javax.swing.JButton();
        delete_Button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        insert_Button = new javax.swing.JButton();
        show_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Accounting_Table = new javax.swing.JTable();
        update_Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        emp_pay_TextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        water_bill_TextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        main_tain_TextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        benefit_TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        apartment_id_TextField = new javax.swing.JTextField();
        clear_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(862, 655));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Accounting");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Accounting_id");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("income");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("electronic_bill");

        menu_Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        menu_Button.setText("menu");
        menu_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ButtonActionPerformed(evt);
            }
        });

        delete_Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        delete_Button.setText("delete");
        delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton4.setText("find");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        insert_Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        insert_Button.setText("insert");
        insert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_ButtonActionPerformed(evt);
            }
        });

        show_Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        show_Button.setText("show");
        show_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_ButtonActionPerformed(evt);
            }
        });

        Accounting_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "accounting_id", "income", "electronic_bill", "water_bill", "employee_pay", "main_tain", "benefit", "apart_id"
            }
        ));
        jScrollPane1.setViewportView(Accounting_Table);

        update_Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        update_Button.setText("update");
        update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("emp_pay");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("water_bill");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("main_tain");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("benefit");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("apartment_id");

        clear_Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        clear_Button.setText("clear");
        clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menu_Button)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(apartment_id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(electronic_bill_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(income_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Accounting_id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emp_pay_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(water_bill_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(main_tain_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(benefit_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(clear_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(show_Button)
                                .addGap(18, 18, 18)
                                .addComponent(insert_Button)
                                .addGap(18, 18, 18)
                                .addComponent(update_Button)
                                .addGap(18, 18, 18)
                                .addComponent(delete_Button)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_Button)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Accounting_id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(income_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(electronic_bill_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(water_bill_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(emp_pay_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(main_tain_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(benefit_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(apartment_id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_Button)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_ButtonActionPerformed
        Accounting_id_TextField.setText("");
        income_TextField.setText("");
        electronic_bill_TextField.setText("");
        water_bill_TextField.setText("");
        emp_pay_TextField.setText("");
        main_tain_TextField.setText("");
        benefit_TextField.setText("");
        apartment_id_TextField.setText("");
    }//GEN-LAST:event_clear_ButtonActionPerformed

    private void show_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_ButtonActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) Accounting_Table.getModel();
            model.setRowCount(0);
            ResultSet rs = my.getData("Accounting");
            while (rs.next()) {
                String accounting_id = rs.getString("acc_id");
                String income = rs.getString("income");
                String electronic_bill = rs.getString("electronic_bill");
                String water_bill = rs.getString("water_bill");
                String emp_pay = rs.getString("emp_pay");
                String main_tain = rs.getString("main_tain");
                String benefit = rs.getString("benefit");
                String apart_id = rs.getString("apart_id");
                model.addRow(new String[]{accounting_id, income, electronic_bill, water_bill, emp_pay, main_tain, benefit, apart_id});
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null,"Err: " + exc);
        }
    }//GEN-LAST:event_show_ButtonActionPerformed

    private void insert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_ButtonActionPerformed
        String accounting_id = Accounting_id_TextField.getText();
        String income = income_TextField.getText();
        String electronic_bil = electronic_bill_TextField.getText();
        String water_bill = water_bill_TextField.getText();
        String emp_pay = emp_pay_TextField.getText();
        String main_tain = main_tain_TextField.getText();
        String benefit = benefit_TextField.getText();
        String apartment_id = apartment_id_TextField.getText();
        try {
            if (my.insertAccountingData(accounting_id, income, electronic_bil, water_bill, emp_pay, main_tain, benefit, apartment_id)) {
                DefaultTableModel model = (DefaultTableModel) Accounting_Table.getModel();
                model.setRowCount(0);
                ResultSet rs = my.getData("Accounting");
                while (rs.next()) {
                    String aaccounting_id = rs.getString("acc_id");
                    String iincome = rs.getString("income");
                    String eelectronic_bill = rs.getString("electronic_bill");
                    String wwater_bill = rs.getString("water_bill");
                    String eemp_pay = rs.getString("emp_pay");
                    String mmain_tain = rs.getString("main_tain");
                    String bbenefit = rs.getString("benefit");
                    String aapartment_id = rs.getString("apart_id");
                    model.addRow(new String[]{aaccounting_id, iincome, eelectronic_bill, wwater_bill, eemp_pay, mmain_tain, bbenefit, aapartment_id});
                }
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null,"Err: " + exc);
        }
    }//GEN-LAST:event_insert_ButtonActionPerformed

    private void update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ButtonActionPerformed
        String accounting_id = Accounting_id_TextField.getText();
        String income = income_TextField.getText();
        String electronic_bil = electronic_bill_TextField.getText();
        String water_bill = water_bill_TextField.getText();
        String emp_pay = emp_pay_TextField.getText();
        String main_tain = main_tain_TextField.getText();
        String benefit = benefit_TextField.getText();
        String apartment_id = apartment_id_TextField.getText();
        try {
            if (my.updateAccountingData(accounting_id, income, electronic_bil, water_bill, emp_pay, main_tain, benefit, apartment_id)) {
                DefaultTableModel model = (DefaultTableModel) Accounting_Table.getModel();
                model.setRowCount(0);
                ResultSet rs = my.getData("Accounting");
                while (rs.next()) {
                    String aaccounting_id = rs.getString("acc_id");
                    String iincome = rs.getString("income");
                    String eelectronic_bill = rs.getString("electronic_bill");
                    String wwater_bill = rs.getString("water_bill");
                    String eemp_pay = rs.getString("emp_pay");
                    String mmain_tain = rs.getString("main_tain");
                    String bbenefit = rs.getString("benefit");
                    String aapartment_id = rs.getString("apart_id");
                    model.addRow(new String[]{aaccounting_id, iincome, eelectronic_bill, wwater_bill, eemp_pay, mmain_tain, bbenefit, aapartment_id});
                }
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null,"Err: " + exc);
        }
    }//GEN-LAST:event_update_ButtonActionPerformed

    private void delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButtonActionPerformed
        String accounting_id = Accounting_id_TextField.getText();
        String income = income_TextField.getText();
        String electronic_bil = electronic_bill_TextField.getText();
        String water_bill = water_bill_TextField.getText();
        String emp_pay = emp_pay_TextField.getText();
        String main_tain = main_tain_TextField.getText();
        String benefit = benefit_TextField.getText();
        String apartment_id = apartment_id_TextField.getText();
        try {
            if (my.deleteAccountingData(accounting_id)) {
                DefaultTableModel model = (DefaultTableModel) Accounting_Table.getModel();
                model.setRowCount(0);
                ResultSet rs = my.getData("Accounting");
                while (rs.next()) {
                    String aaccounting_id = rs.getString("acc_id");
                    String iincome = rs.getString("income");
                    String eelectronic_bill = rs.getString("electronic_bill");
                    String wwater_bill = rs.getString("water_bill");
                    String eemp_pay = rs.getString("emp_pay");
                    String mmain_tain = rs.getString("main_tain");
                    String bbenefit = rs.getString("benefit");
                    String aapartment_id = rs.getString("apart_id");
                    model.addRow(new String[]{aaccounting_id, iincome, eelectronic_bill, wwater_bill, eemp_pay, mmain_tain, bbenefit, aapartment_id});
                }
            }JOptionPane.showMessageDialog(null,"DELETE" );
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null,"Err: " + exc);
        }
    }//GEN-LAST:event_delete_ButtonActionPerformed

    private void menu_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ButtonActionPerformed
        menu m = new menu();
        this.setVisible(false);
        m.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menu_ButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String accounting_id = Accounting_id_TextField.getText();

        try {
            DefaultTableModel model = (DefaultTableModel) Accounting_Table.getModel();
            model.setRowCount(0);
            ResultSet rs = my.getData("Accounting where acc_id = " + "'" + accounting_id + "'");
            while (rs.next()) {
                String aaccounting_id = rs.getString("acc_id");
                String iincome = rs.getString("income");
                String eelectronic_bill = rs.getString("electronic_bill");
                String wwater_bill = rs.getString("water_bill");
                String eemp_pay = rs.getString("emp_pay");
                String mmain_tain = rs.getString("main_tain");
                String bbenefit = rs.getString("benefit");
                String aapartment_id = rs.getString("apart_id");
                model.addRow(new String[]{aaccounting_id, iincome, eelectronic_bill, wwater_bill, eemp_pay, mmain_tain, bbenefit, aapartment_id});
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null,"Err: " + exc);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accounting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Accounting_Table;
    private javax.swing.JTextField Accounting_id_TextField;
    private javax.swing.JTextField apartment_id_TextField;
    private javax.swing.JTextField benefit_TextField;
    private javax.swing.JButton clear_Button;
    private javax.swing.JButton delete_Button;
    private javax.swing.JTextField electronic_bill_TextField;
    private javax.swing.JTextField emp_pay_TextField;
    private javax.swing.JTextField income_TextField;
    private javax.swing.JButton insert_Button;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField main_tain_TextField;
    private javax.swing.JButton menu_Button;
    private javax.swing.JButton show_Button;
    private javax.swing.JButton update_Button;
    private javax.swing.JTextField water_bill_TextField;
    // End of variables declaration//GEN-END:variables
}
